analyzer_rules:
  - unused_declaration
  - unused_import
  - typesafe_array_init

opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - async_without_await
  - closure_end_indentation
  - closure_body_length
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_assert
  - discouraged_none_name
  - discouraged_optional_boolean
  - enum_case_associated_values_count
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - file_types_order
  - final_test_case
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - reduce_into
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - sorted_first_last
  - static_operator
  - superfluous_else
  - toggle_bool
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
disabled_rules:
  - blanket_disable_command
  - trailing_whitespace
  - direct_return
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - file_name
  - force_unwrapping
  - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - no_empty_block
  - no_magic_numbers
  - no_grouping_extension
  - required_deinit
  - strict_fileprivate
  - unowned_variable_capture
  - unused_parameter
  - vertical_parameter_alignment_on_call

strict: false
lenient: false

attributes:
  attributes_with_arguments_always_on_line_above: false
  always_on_line_above:
    - "@ViewBuilder"
enum_case_associated_values_count:
  warning: 3
  error: 4
line_length: 120
closure_body_length: 70
function_body_length:
  warning: 50
  error: 70
function_parameter_count:
  warning: 5
  error: 8
  ignores_default_parameters: true
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1200
large_tuple: 4

number_separator:
  minimum_length: 5
redundant_type_annotation:
  consider_default_literal_types_redundant: false
trailing_comma:
  mandatory_comma: false

type_name:
  max_length: 35
identifier_name:
  min_length: 1
  max_length: 35
  allowed_symbols: ["_"]

reporter: "xcode"
